version: "3.9"

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
      image: fastAPI_image
    container_name: fastAPI_container
    ports:
      - 80:80
    volumes:
      - myvol:/src/app/data/
    command: uvicorn app.main:app --host 0.0.0.0 --port 80

volumes:
  myvol:
  
      

